apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "notation-aws-verifier.configMap" . }}
  namespace: {{ template "notation-aws-verifier.namespace" . }}
  labels:
    {{- include "notation-aws-verifier.labels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
