{{- range $name, $secret := .Values.deployment.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ template "notation-aws-verifier.namespace" $ }}
  labels:
    {{- include "notation-aws-verifier.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "notation-aws-verifier.config.imagePullSecret" $secret }}
{{- end }}
