{{/* vim: set filetype=mustache: */}}

{{- define "notation-aws-verifier.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "notation-aws-verifier.fullname" -}}
{{- if .Values.fullnameOverride -}}
  {{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
  {{- $name := default .Chart.Name .Values.nameOverride -}}
  {{- if contains $name .Release.Name -}}
    {{- .Release.Name | trunc 63 | trimSuffix "-" -}}
  {{- else -}}
    {{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "notation-aws-verifier.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "notation-aws-verifier.namespace" -}}
{{- default .Release.Namespace .Values.namespaceOverride -}}
{{- end -}}

{{- define "notation-aws-verifier.clusterRoleName" -}}
{{- printf "%s-clusterrole" (include "notation-aws-verifier.fullname" .) -}}
{{- end -}}

{{- define "notation-aws-verifier.roleName" -}}
{{- printf "%s-role" (include "notation-aws-verifier.fullname" .) -}}
{{- end -}}

{{- define "notation-aws-verifier.serviceAccountName" -}}
{{- if .Values.serviceAccount.enabled -}}
  {{- default (include "notation-aws-verifier.fullname" .) .Values.serviceAccount.name -}}
{{- else -}}
  {{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end -}}

{{/*
Service name. The TLS secrets generated by the service are named
<serviceName>.<namespace>.svc.tls-pair and <serviceName>.<namespace>.svc.tls-ca.
*/}}
{{- define "notation-aws-verifier.serviceName" -}}
{{- printf "%s-svc" (include "notation-aws-verifier.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "notation-aws-verifier.configMap" -}}
{{- default (include "notation-aws-verifier.fullname" .) .Values.configMap.name -}}
{{- end -}}
